### ISSUE TITLE
Commenting on messages

### ISSUE THREAD

**Issue by edemaine** [edemaine/coauthor#111]
Like GitHub comments on commits, want to be able to comment on a particular line in a particular version of a message.  This is out-of-band commenting, so shows up when looking at a focused view of the history of the message, maybe they show up on the side somehow, can get resolved, and hidden, but can still look back at them. [Jeffrey]

One of GitHub's ways of doing this is that you can paste a link to a specific line, and it inlines the text for you:

https://github.com/edemaine/coauthor/blob/52469c1b081000f3e33182fe27268fd38a342ce6/client/ErrorBoundary.coffee#L4-L6

**Comment by jbosboom** [comment]
When we're writing we often use one long line that gets automatically wrapped by the editor, so we should use spans of characters instead.  (That matches well to the Google Docs UI that also inspired this, where you select a span to comment on.)

We should be careful not to tie them too closely to a particular revision, so that making edits to address one comment doesn't end up hiding others.  Alternately, we could give unresolved comments a button to bring up the revision they're from.

**Comment by edemaine** [comment]
I think this is replaced by
* Quoting the relevant part in the reply (see e.g. #539)
* Minimizing discussions that are resolved
* Splitting messages (currently manual)
* Linking to a specific version (#577)
