### ISSUE TITLE
Deletion of posts with children

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#15]
What happens when I delete a post with children?  Do they get deleted as well, or reparented like Unix processes?  Either way, does undeletion revert that action on the children?  Does it matter if other people wrote them?

(I think I have too many privileges in the 'test' group to see the current behavior.)

**Comment by edemaine** [comment]
Two answers:

When you **delete** a message:
* Most people -- everyone except authors of the message (people who have edited it) and except superusers (with 'super' privilege) -- can no longer see the message.  So this message won't be sent to the local (browser) database.
* Children remain in the database, but...
* As a consequence of the tree traversal of messages, the children *won't* be rendered.  (But they still know their root message.)
I'm not sure of the optimal behavior on that last point.  I could see showing messages without "valid" parents e.g. at the bottom of the root view, so that you could reparent them or delete them if you want.  Thoughts?

When you **superdelete** a message, which is a step after deletion (something you probably haven't tried, because you don't have super privileges, though I just gave you admin privileges so you can now give it to yourself), you are given a choice:
* Superdelete the message and its descendant subtree.
* Superdelete just the message, in which case the children bubble up one level, reparenting to their grandparent.
Note that superdelete destroys the message from all views, and indeed all traces of it -- its history, associated files, etc.  It's for mistakes / database cleanup.  (E.g. I have another feature to superdelete all imported messages, so that I can reimport with a new importer, and not have cruft from the old imports.)

**Comment by jbosboom** [comment]
On 12/20/2015 9:25 AM, edemaine wrote:
> * As a consequence of the tree traversal of messages, the children *won't* be rendered.  (But they still know their root message.)
> I'm not sure of the optimal behavior on that last point.  I could see showing messages without "valid" parents e.g. at the bottom of the root view, so that you could reparent them or delete them if you want.  Thoughts?

Suppose someone asks a question they feel to be a stupid question.  I 
answer it in a reply with clear explanatory text.  They go "oh, duh" and 
delete their question to clean up the thread.  Now I'm not shown the 
explanatory text I wrote.  Given that a coauthor was confused, a reader 
probably will be too, so I might like to put that explanatory text in 
the paper.

Children of deleted posts should definitely be displayed somewhere so I 
can retrieve the content I wrote.

You could consider only showing these posts to their authors as well 
(though would tree traversal reveal further children?).  Given our group 
norms, I don't find authorship very relevant to our use cases except to 
know who to talk to about something they wrote, but it may matter more 
to others.

**Comment by edemaine** [comment]
This makes me wonder whether it'd be useful to have a "Closed" marking, a la Github, where the message is still visible to everyone, but e.g. folded by default so it doesn't clutter the thread.  Could be useful for e.g. shot-down ideas...  Though, perhaps this is better served by a Status field (a whole nother can of worms...).

Anyway, for now, I'll add a display of orphan messages.

**Comment by edemaine** [comment]
It's still the case that, if you delete a root message, the entire thread disappears to everyone who doesn't have access (author of root or superuser).  Perhaps I should display orphans at the group level, too?
