### ISSUE TITLE
Statistics feature appears inaccurate

### ISSUE THREAD

**Issue by jkopinsky** [edemaine/coauthor#158]
None of my authored posts are counting at all (Perhaps it's only counting top level topics, rather than replies?) and I should have 4 mentions but only 3 are counted.

The second thing might be explained if this feature is not retroactive (the not-counted mention is from Feb. 8th).

**Comment by edemaine** [comment]
None of those are the issue.  The issue seems to be that you have *two* users: `jkopin` and `jkopin@mit.edu`.  The @-mentions are inconsistent between the two.  Should I delete one of those users, and if so, which one?  (It's going to take some effort to do so, as I need to re-attribute posts by one of the users to the other...)

**Comment by edemaine** [comment]
Thanks for the bug report.  In fact, the main issue was just that there is an `@` in your username, and that needed some escaping to handle correctly.

**Comment by edemaine** [comment]
I now see 5 @-mentions.  I think the issue was that one of them @-mentioned `jkopin` instead of the correct `jkopin@mit.edu`.

**Comment by jkopinsky** [comment]
I'm not sure if you changed anything, but my statistics are definitely
different now than they were on Wednesday; in particular I have some
authored posts from the last two weeks that weren't showing up before.

Either way, sorry for the username confusion!

**Comment by edemaine** [comment]
Yep, I fixed the stats to correctly handle @s in the usernames.
