### ISSUE TITLE
E-mail notification for my own unpublished post, despite having notifications-for-own-edits off in settings; notification doesn't list a user

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#216]
I received a notification for my own edit to https://coauthor.csail.mit.edu/6.890/m/yW2rEE23QEZjsdLEL , despite having notifications-for-own-posts disabled in my settings.  The notification is strange because it just says " updated root message in thread [...]" where a user name would usually be, and the name is also missing from the e-mail subject.

According to the history slider, no one else has ever edited this post.

**Comment by edemaine** [comment]
Do you get this for every hour of editing, or was this a fluke occurrence?

**Comment by edemaine** [comment]
OK, I figured out part of the story: somehow you (I assume) caused an update with an empty list of `updators`.  That empty list didn't have your username in it, so you got notified, with a weird notification message.  Still tracking down how this could have happened...

**Comment by jbosboom** [comment]
This is the first and only time I've received a notification about that post.

**Comment by edemaine** [comment]
OK, I tracked down the cause.  Previously, if you edited a post and then immediately stopped editing, your username would be removed from the `updators` list before the diff/update got added to the database.  If you were the only editor, this would result in a diff with no updators.  If this was the *only* update in a 1-hour (or whatever) period, you'd end up with an entire notification that had no `updators`, so every subscriber would get notifications about it.  Maybe not all of these conditions were required...

Anyway, I now store the active list of updators when the update happens, instead of grabbing it after the internal 1-second delay after the update.  So this shouldn't be possible anymore.  (But let me know if you see it again.)
