### ISSUE TITLE
Embedded image submessages not being folded

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#220]
https://coauthor.csail.mit.edu/6.890/m/8uW6TJwbtGrj4LFyc references its attached images, but the image submessages are not folded.

**Comment by edemaine** [comment]
The issue here is that this page links directly to the old-style file URLs (e.g. https://coauthor.csail.mit.edu/gridfs/fs/id/63c1e46ed339ac98db54b5e8), instead of the new-style URLs (e.g. https://coauthor.csail.mit.edu/file/fGfQznZBDFDYg9NgL).  The old-style URLs still resolve render, but the image attachment detector does not.  Is this worth fixing, to support some old content, or should we just update the content?  I think it wouldn't be too hard to add support, so maybe worth doing...

**Comment by edemaine** [comment]
Fixed. Also added support for absolute forms of file URLs.
