### ISSUE TITLE
svg not rendering correctly

### ISSUE THREAD

**Issue by jkopinsky** [edemaine/coauthor#269]
svgs are not rendering correctly for me on my Macbook OS10.11.6

Specfically, none of the svgs here are rendering correctly (but opening the images in a new tab works fine):
https://coauthor.csail.mit.edu/Barbados2017/m/KH7W3pcbXwj3JGwn5

Screenshot:
![image](https://user-images.githubusercontent.com/1958025/33344473-1cfd88b6-d457-11e7-9fc8-33efedaa8256.png)

**Comment by edemaine** [comment]
@jkopinsky Is that screenshot supposed to be wrong in some way?  I must be missing it.

Also, which browser?

**Comment by jkopinsky** [comment]
Chrome (oops should have mentioned that; it apparently is fine on Safari).

The screenshot shows an svg which appears to be missing what seems like a random subset of its objects. To see the  correct one, follow the link to the original thread and either you will see a working version to compare to, or you will see a broken version and you can open the image in its own tab for what will likely be a correct rendering.

**Comment by edemaine** [comment]
Thanks; sorry for missing the obvious errors initially.

This turned out to be a bug in svgtiler, fixed in svgtiler 1.3.4 (specifically https://github.com/edemaine/svgtiler/commit/96a74e9a69443077dbc369fface51b1b20022e90).  Basically, the names of symbols used to include colons fairly often, and Chrome seems to have trouble with those.  I haven't found any documentation for why colons are bad, but I'm now using a pretty reasonable escaping standard (instead of a hand-rolled one) that should avoid this issue in the future.  Especially weird that colons are problematic in an embedded `<img>` but not when rendering the SVG "straight".

(I also recompiled the momentum figures and updated the Coauthor thread accordingly.)
