### ISSUE TITLE
Option to disable autosave

### ISSUE THREAD

**Issue by jnhnum1** [edemaine/coauthor#288]
I'm often not ready for people to read half-composed comments, and it seems there's no reason for anybody (even admins with super-viewing powers) to be able to see such comments.  So why not have an option to disable auto-saving?

**Comment by edemaine** [comment]
I'm afraid that's not possible, given the way Coauthor is built. Everything is synchronized with the server by design.

However, this is the intent of "unpublished" messages. If you have an incomplete thought, make the message unpublished, and publish when you're done with it. You can set your new posts to be initially unpublished if you find yourself using this feature a lot. Just don't forget to publish when you're done! 

It's true that superusers can still see these posts, but only if they click "Become Superuser".
