### ISSUE TITLE
Downloading attached files

### ISSUE THREAD

**Issue by qqliu** [edemaine/coauthor#289]
It seems like the only option available right now is if you click on the file, the file opens in a separate tab. However, it seems like a valid option for files that aren't PDFs is to download them to your computer instead of viewing a text version of the file (this is bad in the case of binary files for example).

**Comment by edemaine** [comment]
Can you link me an example of a file where you see weird behavior?  Perhaps it has the wrong content-type set...

The browser is supposed to handle this behavior correctly automatically: show in browser if it's an accepted content-type, and download otherwise.  If there's a file that you want to download anyway, you can always right click and select "Save link as..." or (in Chrome) ALT-click the link on Windows or OPTION-click the link on MacOS.  I could add a Download button to force this behavior (is this what Gmail presents?) but I'm not sure it's worth the interface clutter... Open to opinions!

**Comment by qqliu** [comment]
The file at this link opens in a new tab as opposed to being downloaded to the user's computer:https://coauthor.csail.mit.edu/file/dYAHK2GhooiDxMTDC

I think Gmail auto-downloads or displays the file based on content type.  It's probably not worth the UI clutter to add a download button.

**Comment by edemaine** [comment]
Thanks. That file had a content-type of the empty string, I guess because the original upload failed to detect a good content-type for a filename of `something.maple`.  There's now a default of `application/octet-stream` which should download the file.
