### ISSUE TITLE
Make the 'Stop Editing' button more prominent; de-emphasize Delete

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#30]
When I'm done editing, my attention is drawn to the Delete button because it's colored red, compared to the Stop Editing (or Commit (#28)) button, which is white.  That the Stop Editing button has moved left of where the Edit button was, but the Delete button did not move, also makes this more prominent.

I think the button bar should be reordered to place Edit/Stop Editing furthest on the right, where it will not move when other buttons appear/disappear, and color it green.  (I'd suggest blue for Edit, as for some reason blue is associated with editing to me, but the header is already blue so that won't work.)  Editor option buttons/dropdowns should then appear directly to the left of Edit (or somewhere else, they seem unimportant).  Delete should be moved to the left of this right-justified set of buttons, and should be just a link rather than a button, to reflect the fact that we're not going to click it often and clicking it is (slightly) dangerous.

**Comment by edemaine** [comment]
The one thing I didn't do is make Delete a link instead of a button.  Buttons not links should do actions, so this feels like bad UI design to me.  However, I do think that Delete should be hidden under a drop-down of less-popular/more-dangerous operations.  Not sure what else would go there, though... maybe 'Move to different thread'.
