### ISSUE TITLE
Stop editing when closing the browser window

### ISSUE THREAD

**Issue by slef** [edemaine/coauthor#306]
It might be nicer if messages would close the editing mode when closing the browser window, or after the text hasn't been touched for some time. 
I sometimes edit long posts, check the result and then close the window forgetting to stop editing. It feels weird to see the edit window open a week later while looking at the post.

**Comment by edemaine** [comment]
I don't know whether we can really detect browser window closing, but I suggest a timeout (say, an hour) where if, no edits have happened in the meantime, that person/everyone stops editing the message.

**Comment by jbosboom** [comment]
Sending data on page unload is what [`Navigator.sendBeacon`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) is for (but some people block it because it's generally used for tracking).  I don't know if user agents bother to run unload handlers when the user closes the browser, and of course it won't run if the browser crashed.

**Comment by edemaine** [comment]
I've implemented basic idle detection: if a message body doesn't get touched by anyone for 1 hour, then everyone stops editing it.  This is certainly the easiest approach, and should suffice for detecting "forget about it for days" without adversely affecting real edit sessions.
