### ISSUE TITLE
Obvious way to return to top of group

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#31]
Currently the 'Coauthor' link in the upper-left returns to the top level of the group, but I expect it to return to the very top level of the application (shown at the root URL).  Instead I tried middle-clicking on the group selector dropdown to open it in a new tab -- it shows the name of the current group, so obviously that's how to get to the group level, right?  Instead it opened a new tab pointing at the top-level message I was viewing.

Not sure what the right UI is here.  Requiring clicking on that little dropdown triangle icon to change groups is annoying, and moving to the very top level of the application should be rare, so using the prominent 'Coauthor' link for that would be a waste.

**Comment by edemaine** [comment]
I'd suggest changing the Coauthor link to go to the top level, because that is most natural, and we switch the dropdown to a "[split dropdown](http://getbootstrap.com/components/#btn-dropdowns-split)" which has a button to go to the current group as well as a caret to switch groups.  (Even if people don't see the caret, they can go to the top level and select their group there.)

**Comment by edemaine** [comment]
I ended up finding a way to hack this together using regular drop-downs instead of split button dropdowns, thereby avoiding the button box, which seems preferable.
