### ISSUE TITLE
Title of post does not wrap

### ISSUE THREAD

**Issue by tomhull0** [edemaine/coauthor#418]
If someone, for example an excited college student, gives a post a title with a word made entirely of 40-50 letter "a"s (as in "Yeaaaaaaaaaaaaaaa....aaaaaaa"), then it doesn't wrap around.  See, for example:
https://coauthor.csail.mit.edu/MathILy-EST-2019/m/nxdd6eHvai5hTrtGs

**Comment by edemaine** [comment]
This should have been easy with an `overflow-wrap` setting, but it wasn't so simple because of the way message titles were wrapping in inline-blocks, which was a hack.  This was a good excuse to fix the layout using inline elements, which improves other aspects of the layout (notably, right buttons can share last line with a multiline title).

Thanks for reporting!  Good motivation to clean this up.
