### ISSUE TITLE
Internal message links

### ISSUE THREAD

**Issue by tiborschneider** [edemaine/coauthor#586]
Unfortunately, adding the `id` attribute to HTML tags in a message does not allow a link to point to that element:

```html
<a href="#ImportantSection">Link to section</a>
<h3 id="ImportantSection">Important Section</h3>
```

The link works, and appends the `#ImportantSection` to the url, but the page does not move (neither in HTML mode, nor in Markdown mode). It would be very nice to have working links inside of a message for longer posts.

**Comment by edemaine** [comment]
The issue is that Coauthor's HTML sanitizer removes `id` attributes, because (I believe) it's a security risk. Also, multiple messages with the same `id`s will cause problems, as `id`s need to be globally unique.

Maybe we could transform `id="ImportantSection"` to `id="messageID-ImportantSection"` where `messageID` is the unique message ID.  And if we want to get fancy, we could also autotranslate the link `#ImportantSection` to `#messageID-ImportantSection`.

It might also be nice to add automatic `id`s to Markdown sections (`## Important Section` -> `<h2 id="messageID-important-section">Important Section</h2>`).  I imagine there's a plugin for this.

**Comment by tiborschneider** [comment]
<p id="thanks">Thanks for the quick response</p>

I cannot say anything about the security aspect, except that GitHub themselves seem to allow ID attributes in their markdown / html sanitizer, as you can see from this <a href="#thanks">link to the first line</a>.

About the uniqueness, I think if we automatically transform the attributes, we should also do this for the links. However, I also think that it is acceptable if links are not necessarily unique, since as an author, you can always make the link unique.

And yes, there is a [plugin](https://www.npmjs.com/package/markdown-it-anchor) for automatically adding the anchors to headings (which is based on markdown-it, which is also what you are using if I understand it correctly).

**Comment by edemaine** [comment]
I now really want this feature so that I can inline SVG content with `<use>` (which requires elements to have `id`s). I'll probably implement it soon as a result.
