### ISSUE TITLE
Combine publish and deleted

### ISSUE THREAD

**Issue by edemaine** [edemaine/coauthor#7]
There should be one field with three options: unpublished (pre-publication), published, and deleted (post-publication).  Or should we bother with the unpublished state at all?

**Comment by jbosboom** [comment]
On the site, unpublished/hidden serves only to save users one click to see that the contents are not complete (but even in that case they might want to follow along).  It might be useful to not send e-mail notifications for such posts, depending on how fine-grained notifications are.

I think unpublished can be combined with deleted, at least logically; if posts start out 'deleted', the button might say 'Publish' instead of 'Undelete' before its first pressing (controlled by looking for previous undelete events in the history).

**Comment by edemaine** [comment]
Yes, this seems right.  I believe your proposal is equivalent to adding to the current system the constraint "once published, you can't unpublish" (at least not in the UI) -- instead, just use Delete.  This is a trivial tweak (just never show the Unpublish button), but has the big plus of reducing the number of visible buttons to always 1.

The only downside to this approach is that we keep the complication in the database.  Currently, a message has a Boolean `deleted` flag as well as a `published` value which is either `null` to indicate unpublished or the date published (which can be later than the `created` date).  Maybe this isn't so bad.

**Comment by jbosboom** [comment]
I propose that 'unpublished' _is_ deleted, with the undelete button being labeled 'Publish' if the post has been deleted for its entire life.  There is no need for a separate 'published' value, assuming your history tracks delete/undelete events (which it should, along with reparenting, file-was-attached, etc.).

**Comment by edemaine** [comment]
Deciding which buttons to display should not require looking into the entire history of the message.  (They are different databases, and the history one is far larger.)  The correct way to implement this ability would be have a flag to indicate whether the message was (ever) published/undeleted.  Guess what: that's `published`.
